server:
  port: 8002

mybatis:
  config-location: classpath:mybaties/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mybaties/mapper/*.xml       # mapper映射文件
  type-aliases-package: entities

spring:
  application:
    name: microservicecloud
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/ssh2              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
#      生产者注册eureka地址（与eureka设置的service-url相同）
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
#    注册进入eureka的显示实例名称
    instance-id: microservice8002
#    显示注册进入eureka实例名称的ip
    prefer-ip-address: true

# 与spring-boot-starter-actuator依赖搭配使用
info:
  app.name: microservicecloud
  company.name: alibaba
  build.artifactId: microservicecloud
  build.version: 1.0-SNAPSHOT